name: Speculus
description: An app to record your mood and your activities.


version: 1.0.3+3

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_messaging: ^5.1.6

  fl_chart: ^0.3.4
  table_calendar: ^2.1.0
  flutter_circular_slider : ^2.5.0
  sqflite: ^1.1.7+1
  path_provider: ^1.4.0
  cloud_firestore: ^0.12.9
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  link: ^1.0.0
  url_launcher:
  uuid: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "icon/logo1.png"


flutter:

  uses-material-design: true


